In [16]:
import numpy as np
import xarray as xr
from remake import load_remake

In [3]:
e5h = load_remake('../../remakefiles/era5_histograms.py')

loading pixel inputs cache


In [4]:
t = e5h.ConditionalERA5HistDC.tasks[0]

In [9]:
t.inputs['pixel_on_e5_2001-01-01 00:30:00']

PosixPath('/gws/nopw/j04/mcs_prime/mmuetz/data/mcs_prime_output/mcs_track_pixel_on_era5_grid/2001/01/01/mcstrack_on_era5_grid_200101010030.nc')

In [11]:
ds = xr.open_dataset(t.inputs['pixel_on_e5_2001-01-01 00:30:00'])

In [12]:
ds

<xarray.Dataset>
Dimensions:        (latitude: 481, longitude: 1440, time: 1)
Coordinates:
  * time           (time) datetime64[ns] 2001-01-01T00:30:00
  * latitude       (latitude) float32 60.0 59.75 59.5 ... -59.5 -59.75 -60.0
  * longitude      (longitude) float32 0.0 0.25 0.5 0.75 ... 359.2 359.5 359.8
Data variables:
    cloudnumber    (latitude, longitude) int16 ...
    tb             (latitude, longitude) float32 ...
    precipitation  (latitude, longitude) float32 ...
Attributes: (12/20)
    description:                     Pixel data from Feng et al. 2021 (https:...
    regridding:                      Regridded onto ERA5 grid
    created by:                      /home/users/mmuetz/projects/mcs_prime/ct...
    calling file source:             """Remakefile to do processing of ERA5/M...
    project repository:              https://github.com/markmuetz/MCS_PRIME
    remake version:                  ['0', '6', '3', '0', 'beta']
    ...                              ...
    production_mcs_prime_git_info:   GitInfo(loc='/home/users/mmuetz/projects...
    production_remake_git_info:      GitInfo(loc='/home/users/mmuetz/projects...
    production_conda_env_details:    name: mcs_prime_env\nchannels:\n  - cond...
    production_machine_lspcu:        Architecture:          x86_64\nCPU op-mo...
    production_machine_lsb_release:  Distributor ID:\tCentOS\nDescription:\tC...
    production_machine_uname:        Linux host398.jc.rl.ac.uk 3.10.0-1160.92...

In [25]:
ds.longitude.values

array([0.0000e+00, 2.5000e-01, 5.0000e-01, ..., 3.5925e+02, 3.5950e+02,
       3.5975e+02], dtype=float32)

In [14]:
len(ds.longitude.values)

1440

In [15]:
1440 / 24

60.0

In [23]:
dc_idx = np.repeat(np.arange(24), 60)

In [58]:
ds.longitude.values[dc_idx == 23]

array([345.  , 345.25, 345.5 , 345.75, 346.  , 346.25, 346.5 , 346.75,
       347.  , 347.25, 347.5 , 347.75, 348.  , 348.25, 348.5 , 348.75,
       349.  , 349.25, 349.5 , 349.75, 350.  , 350.25, 350.5 , 350.75,
       351.  , 351.25, 351.5 , 351.75, 352.  , 352.25, 352.5 , 352.75,
       353.  , 353.25, 353.5 , 353.75, 354.  , 354.25, 354.5 , 354.75,
       355.  , 355.25, 355.5 , 355.75, 356.  , 356.25, 356.5 , 356.75,
       357.  , 357.25, 357.5 , 357.75, 358.  , 358.25, 358.5 , 358.75,
       359.  , 359.25, 359.5 , 359.75], dtype=float32)

In [33]:
-1 % 24

23

In [40]:
h = 1
lst = 2
ds.longitude.values[dc_idx == (lst - h) % 24]

array([15.  , 15.25, 15.5 , 15.75, 16.  , 16.25, 16.5 , 16.75, 17.  ,
       17.25, 17.5 , 17.75, 18.  , 18.25, 18.5 , 18.75, 19.  , 19.25,
       19.5 , 19.75, 20.  , 20.25, 20.5 , 20.75, 21.  , 21.25, 21.5 ,
       21.75, 22.  , 22.25, 22.5 , 22.75, 23.  , 23.25, 23.5 , 23.75,
       24.  , 24.25, 24.5 , 24.75, 25.  , 25.25, 25.5 , 25.75, 26.  ,
       26.25, 26.5 , 26.75, 27.  , 27.25, 27.5 , 27.75, 28.  , 28.25,
       28.5 , 28.75, 29.  , 29.25, 29.5 , 29.75], dtype=float32)

In [53]:
dc_idx2 = np.tile(dc_idx, (481, 1))

In [55]:
ds.precipitation.values[dc_idx2 == 0]

array([1.7048376e+00, 2.0814700e+00, 2.0667222e+00, ..., 1.1296148e-04,
       1.1294015e-04, 1.1296148e-04], dtype=float32)

In [56]:
dc_idx2.shape

(481, 1440)