# New env vars

After talking to people and getting feedback at 20Meso and my trip to NCAR/Mesa Labs, there were several suggestions for new/different environmental vars to look at.
These were:

* deep shear (Xingchao Chen found this to be important)
* MSE/theta_e (various, including Mitch. Needs choice of level)
* RH (cannot remember but seems sensible. Again, choice of level)
* PBL vars (what? Cannot remember who)

Here, I will check that I can calculate these from ERA5 data.

In [42]:
import metpy.calc as mcalc
from metpy.units import units
import numpy as np
import xarray as xr

from remake.util import format_path as fmtp

from mcs_prime import mcs_prime_config_util as cu
from mcs_prime import era5_calc

In [3]:
cu.PATHS['era5dir']

PosixPath('/badc/ecmwf-era5')

In [13]:
globpath = fmtp(cu.FMT_PATH_ERA5_ML, year=2020, month=1, day=1, hour=0, var='*')
parent = globpath.parent
paths = sorted(parent.glob(globpath.name))
paths

[PosixPath('/badc/ecmwf-era5/data/oper/an_ml/2020/01/01/ecmwf-era5_oper_an_ml_202001010000.lnsp.nc'),
 PosixPath('/badc/ecmwf-era5/data/oper/an_ml/2020/01/01/ecmwf-era5_oper_an_ml_202001010000.o3.nc'),
 PosixPath('/badc/ecmwf-era5/data/oper/an_ml/2020/01/01/ecmwf-era5_oper_an_ml_202001010000.q.nc'),
 PosixPath('/badc/ecmwf-era5/data/oper/an_ml/2020/01/01/ecmwf-era5_oper_an_ml_202001010000.t.nc'),
 PosixPath('/badc/ecmwf-era5/data/oper/an_ml/2020/01/01/ecmwf-era5_oper_an_ml_202001010000.u.nc'),
 PosixPath('/badc/ecmwf-era5/data/oper/an_ml/2020/01/01/ecmwf-era5_oper_an_ml_202001010000.v.nc'),
 PosixPath('/badc/ecmwf-era5/data/oper/an_ml/2020/01/01/ecmwf-era5_oper_an_ml_202001010000.vo.nc'),
 PosixPath('/badc/ecmwf-era5/data/oper/an_ml/2020/01/01/ecmwf-era5_oper_an_ml_202001010000.z.nc')]

In [16]:
ds = xr.open_mfdataset(paths)
ds

<xarray.Dataset>
Dimensions:    (longitude: 1440, latitude: 721, time: 1, level: 137)
Coordinates:
  * longitude  (longitude) float32 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
  * latitude   (latitude) float32 90.0 89.75 89.5 89.25 ... -89.5 -89.75 -90.0
  * time       (time) datetime64[ns] 2020-01-01
  * level      (level) int32 1 2 3 4 5 6 7 8 ... 130 131 132 133 134 135 136 137
Data variables:
    lnsp       (time, latitude, longitude) float32 dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    o3         (time, level, latitude, longitude) float32 dask.array<chunksize=(1, 137, 721, 1440), meta=np.ndarray>
    q          (time, level, latitude, longitude) float32 dask.array<chunksize=(1, 137, 721, 1440), meta=np.ndarray>
    t          (time, level, latitude, longitude) float32 dask.array<chunksize=(1, 137, 721, 1440), meta=np.ndarray>
    u          (time, level, latitude, longitude) float32 dask.array<chunksize=(1, 137, 721, 1440), meta=np.ndarray>
    v          (time, level, latitude, longitude) float32 dask.array<chunksize=(1, 137, 721, 1440), meta=np.ndarray>
    vo         (time, level, latitude, longitude) float32 dask.array<chunksize=(1, 137, 721, 1440), meta=np.ndarray>
    z          (time, latitude, longitude) float32 dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
Attributes:
    Conventions:  CF-1.6
    history:      2020-04-06 11:19:13 GMT by grib_to_netcdf-2.14.0: grib_to_n...

In [19]:
e5calc = era5_calc.ERA5Calc(cu.PATH_ERA5_MODEL_LEVELS)

In [26]:
p = e5calc.calc_pressure(ds['lnsp'].values[0])

In [27]:
p.shape

(137, 721, 1440)

In [29]:
p.mean(axis=(1, 2))

array([1.00018250e+00, 2.55130300e+00, 3.88416250e+00, 5.74703050e+00,
       8.28747150e+00, 1.16761950e+01, 1.61071775e+01, 2.17973245e+01,
       2.89857140e+01, 3.79324760e+01, 4.89173525e+01, 6.22380195e+01,
       7.82082290e+01, 9.71558115e+01, 1.19420624e+02, 1.45352456e+02,
       1.75308983e+02, 2.09653755e+02, 2.48754264e+02, 2.92980163e+02,
       3.42701554e+02, 3.98287430e+02, 4.60104263e+02, 5.28514740e+02,
       6.03876678e+02, 6.86542023e+02, 7.76855988e+02, 8.75156372e+02,
       9.81773041e+02, 1.09702741e+03, 1.22123199e+03, 1.35469025e+03,
       1.49769653e+03, 1.65053595e+03, 1.81348413e+03, 1.98680762e+03,
       2.17076379e+03, 2.36560107e+03, 2.57155933e+03, 2.78886975e+03,
       3.01775537e+03, 3.25843152e+03, 3.51110596e+03, 3.77597937e+03,
       4.05321057e+03, 4.34287402e+03, 4.64498340e+03, 4.95952222e+03,
       5.28644287e+03, 5.62566772e+03, 5.97720947e+03, 6.34151050e+03,
       6.71940869e+03, 7.11186987e+03, 7.51997866e+03, 7.94488008e+03,
      

In [30]:
ds.q

<xarray.DataArray 'q' (time: 1, level: 137, latitude: 721, longitude: 1440)>
dask.array<open_dataset-30c012ff6b2a3b93ed3569580a59b27fq, shape=(1, 137, 721, 1440), dtype=float32, chunksize=(1, 137, 721, 1440), chunktype=numpy.ndarray>
Coordinates:
  * longitude  (longitude) float32 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
  * latitude   (latitude) float32 90.0 89.75 89.5 89.25 ... -89.5 -89.75 -90.0
  * time       (time) datetime64[ns] 2020-01-01
  * level      (level) int32 1 2 3 4 5 6 7 8 ... 130 131 132 133 134 135 136 137
Attributes:
    units:          kg kg**-1
    long_name:      Specific humidity
    standard_name:  specific_humidity

In [49]:
from importlib import reload
reload(era5_calc)
e5calc = era5_calc.ERA5Calc(cu.PATH_ERA5_MODEL_LEVELS)

In [57]:
# calc theta_e at model level -10 (10 above surf)
theta_e = e5calc.calc_theta_e(p[-10], ds.t.values[0][-10], ds.q.values[0][-10])
theta_e

array([[250.34177699, 250.34177699, 250.34177699, ..., 250.34177699,
        250.34177699, 250.34177699],
       [250.53501703, 250.53501703, 250.53729468, ..., 250.53134342,
        250.53134342, 250.5336211 ],
       [250.76248854, 250.76299277, 250.76299277, ..., 250.76588483,
        250.76499979, 250.76499979],
       ...,
       [277.32550128, 277.33162359, 277.33522881, ..., 277.31464344,
        277.31823895, 277.32183467],
       [277.05109048, 277.05295743, 277.05475365, ..., 277.04733631,
        277.04660472, 277.0483919 ],
       [276.73704877, 276.73704877, 276.73704877, ..., 276.73704877,
        276.73704877, 276.73704877]])

In [58]:
# calc RH at model level -10 (10 above surf)
RH = e5calc.calc_RH(p[-10], ds.t.values[0][-10], ds.q.values[0][-10])

In [51]:
RH

array([[0.81838936, 0.81838936, 0.81838936, ..., 0.81838936, 0.81838936,
        0.81838936],
       [0.84984973, 0.84984973, 0.84967591, ..., 0.85091767, 0.85091767,
        0.85074348],
       [0.79411027, 0.79254035, 0.79254035, ..., 0.79549835, 0.79479533,
        0.79479533],
       ...,
       [0.66091664, 0.66075079, 0.66072072, ..., 0.66100722, 0.66097722,
        0.66094722],
       [0.67347541, 0.67345953, 0.67344424, ..., 0.67339008, 0.67351358,
        0.67349837],
       [0.69464864, 0.69464864, 0.69464864, ..., 0.69464864, 0.69464864,
        0.69464864]])

In [56]:
print(p.shape)
p[-1] / 100

(137, 721, 1440)


array([[998.20900021, 998.20900021, 998.20900021, ..., 998.20900021,
        998.20900021, 998.20900021],
       [998.19760748, 998.19760748, 998.19760748, ..., 998.19760748,
        998.19760748, 998.19760748],
       [998.04817539, 998.04817539, 998.04817539, ..., 998.02538992,
        998.02538992, 998.02538992],
       ...,
       [693.67959257, 693.64783337, 693.61599615, ..., 693.77549442,
        693.74373522, 693.71197603],
       [691.98738147, 691.97091663, 691.95507605, ..., 692.04278449,
        692.02694391, 692.01118136],
       [690.74448105, 690.74448105, 690.74448105, ..., 690.74448105,
        690.74448105, 690.74448105]])

Chen, Liu and Mapes (2017) define 2 useful RH values, both of which have predictive value. RHlow: avg over 1000-850 hPa layer. RHmid: avg over 700-400 hPa. Calc these below:

In [59]:
# 114: 856 hPa - https://confluence.ecmwf.int/display/UDOC/L137+model+level+definitions
RHlow = e5calc.calc_RH(p[114:], ds.t.values[0][114:], ds.q.values[0][114:]).mean(axis=0)

In [61]:
# 90: 407 hPa - https://confluence.ecmwf.int/display/UDOC/L137+model+level+definitions
# 105: 703 hPa - https://confluence.ecmwf.int/display/UDOC/L137+model+level+definitions
RHmid = e5calc.calc_RH(p[90:106], ds.t.values[0][90:106], ds.q.values[0][90:106]).mean(axis=0)

Chen et al. (2023) show that theta_e has the largest impact just before MCS init in layer 850-750 hPa (their Fig. 1).
Use this to define theta_e layer: theta_e_mid

In [62]:
# 107: 742 hPa
# 114: 857 hPa
theta_e_mid = e5calc.calc_theta_e(p[107:115], ds.t.values[0][107:115], ds.q.values[0][107:115]).mean(axis=0)
theta_e_mid

array([[265.24769582, 265.24769582, 265.24769582, ..., 265.24769582,
        265.24769582, 265.24769582],
       [265.28160966, 265.28215469, 265.28252616, ..., 265.2789796 ,
        265.27927681, 265.28048219],
       [265.32425881, 265.32556069, 265.3265818 , ..., 265.31936753,
        265.32114285, 265.32387826],
       ...,
       [284.84839297, 284.85011453, 284.85105145, ..., 284.84697902,
        284.84797959, 284.84785561],
       [284.67023856, 284.67054321, 284.67083739, ..., 284.6689995 ,
        284.66929063, 284.66946028],
       [284.20031282, 284.20031282, 284.20031282, ..., 284.20031282,
        284.20031282, 284.20031282]])